spring:
  profiles:
    active: local


# local
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/demomarket
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: your@gmail.com
    password: yourpw
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

